package generators

import (
	"fmt"
	"os"
	"strings"
	"time"
)

func generateClaudeMD(cfg Config) error {
	var sb strings.Builder

	projectName := cfg.ProjectName
	if projectName == "" {
		projectName = "my-project"
	}

	sb.WriteString(fmt.Sprintf("# %s — Claude Code Instructions\n\n", projectName))
	sb.WriteString(fmt.Sprintf("> Generated by trackfw on %s. Update this file as the project evolves.\n\n", time.Now().Format("2006-01-02")))

	sb.WriteString("## Project overview\n\n")
	sb.WriteString("<!-- Describe what this project does in 2-3 sentences. -->\n\n")

	sb.WriteString("## Governance chain\n\n")
	sb.WriteString("trackfw enforces the following traceability chain:\n\n")
	sb.WriteString("ADR → REQ → ROADMAP → backlog/wip/blocked/done/abandoned\n\n")
	sb.WriteString("Rules:\n")
	sb.WriteString("- Every piece of work must have a REQ linked to an ADR\n")
	sb.WriteString("- Every REQ must have a linked ROADMAP\n")
	sb.WriteString("- `trackfw validate` must pass before every commit\n")
	sb.WriteString("- Only one roadmap in `wip/` at a time — complete or block it before starting another\n\n")

	sb.WriteString("## Governance commands\n\n")
	sb.WriteString("| Command | When to use |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString("| `trackfw adr new \"title\"` | Before any architectural or technical decision |\n")
	sb.WriteString("| `trackfw req new \"title\"` | Before any implementation work |\n")
	sb.WriteString("| `trackfw roadmap new \"title\"` | After REQ is created and approved |\n")
	sb.WriteString("| `trackfw roadmap move <name> wip` | When starting implementation |\n")
	sb.WriteString("| `trackfw roadmap move <name> done` | When implementation is complete |\n")
	sb.WriteString("| `trackfw validate` | Before every commit — must pass with zero violations |\n")
	sb.WriteString("| `trackfw status` | Check what is in flight |\n\n")

	// Frontend section
	if cfg.Frontend != "" && cfg.Frontend != "none" {
		pm := cfg.PkgManager
		if pm == "" || pm == "none" {
			pm = "npm"
		}
		sb.WriteString("## Frontend\n\n")
		sb.WriteString(fmt.Sprintf("Stack: %s\n", cfg.Frontend))
		sb.WriteString(fmt.Sprintf("Package manager: %s\n\n", pm))
		sb.WriteString("Build commands:\n")
		sb.WriteString(fmt.Sprintf("  %s run build     # build\n", pm))
		sb.WriteString(fmt.Sprintf("  %s run dev       # dev server\n", pm))
		sb.WriteString(fmt.Sprintf("  %s run test      # tests\n\n", pm))
		sb.WriteString("Rules:\n")
		sb.WriteString(fmt.Sprintf("- Build must pass (`%s run build`) before marking any ML as done\n", pm))
		sb.WriteString("- Run `trackfw validate` before committing frontend changes\n\n")
	}

	// Backend section
	if cfg.Backend != "" && cfg.Backend != "none" {
		buildCmd, testCmd, lintCmd := backendCommands(cfg)
		sb.WriteString("## Backend\n\n")
		sb.WriteString(fmt.Sprintf("Stack: %s\n\n", cfg.Backend))
		sb.WriteString("Build commands:\n")
		sb.WriteString(fmt.Sprintf("  %s   # build / compile check\n", buildCmd))
		sb.WriteString(fmt.Sprintf("  %s   # tests\n", testCmd))
		sb.WriteString(fmt.Sprintf("  %s   # lint / vet\n\n", lintCmd))
		sb.WriteString("Rules:\n")
		sb.WriteString("- Build must pass before marking any ML as done\n")
		sb.WriteString("- Run `trackfw validate` before committing backend changes\n\n")
	}

	// Pre-commit checklist
	sb.WriteString("## Pre-commit checklist\n\n")
	sb.WriteString("Before every commit:\n")
	sb.WriteString("- [ ] `trackfw validate` passes with zero violations\n")
	if cfg.Backend != "" && cfg.Backend != "none" {
		buildCmd, _, _ := backendCommands(cfg)
		sb.WriteString(fmt.Sprintf("- [ ] `%s` passes\n", buildCmd))
	}
	if cfg.Frontend != "" && cfg.Frontend != "none" {
		pm := cfg.PkgManager
		if pm == "" || pm == "none" {
			pm = "npm"
		}
		sb.WriteString(fmt.Sprintf("- [ ] `%s run build` passes\n", pm))
	}
	sb.WriteString("\n")

	// Git hooks section
	sb.WriteString("## Git hooks\n\n")
	switch cfg.Hooks {
	case "husky":
		sb.WriteString("Git hook configured in `.husky/pre-commit` — runs `trackfw validate` automatically.\n\n")
	case "lefthook":
		sb.WriteString("Git hook configured in `lefthook.yml` — runs `trackfw validate` automatically.\n\n")
	default:
		sb.WriteString("No git hook configured. Run `trackfw validate` manually before every commit.\n\n")
	}

	// CI gate section
	sb.WriteString("## CI gate\n\n")
	switch cfg.CI {
	case "github-actions":
		sb.WriteString("`.github/workflows/trackfw-gate.yml` runs `trackfw validate` on every pull request to main.\n")
	case "gitlab-ci":
		sb.WriteString("`.gitlab-ci-trackfw.yml` runs `trackfw validate` on every merge request.\n")
	default:
		sb.WriteString("No CI gate configured.\n")
	}

	if err := os.WriteFile("CLAUDE.md", []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("writing CLAUDE.md: %w", err)
	}
	fmt.Println("  ✓ CLAUDE.md")
	return nil
}

// backendCommands retorna (buildCmd, testCmd, lintCmd) para o backend configurado.
func backendCommands(cfg Config) (string, string, string) {
	pm := cfg.PkgManager
	if pm == "" || pm == "none" {
		pm = "npm"
	}
	switch cfg.Backend {
	case "go":
		return "go build ./...", "go test ./...", "go vet ./..."
	case "java":
		return "mvn package -q", "mvn test", "mvn compile -q"
	case "node":
		return pm + " run build", pm + " test", pm + " run lint"
	case "python":
		return "python -m py_compile $(find . -name '*.py' -not -path './.venv/*' -not -path './venv/*')",
			"python -m pytest",
			"ruff check ."
	default:
		return "", "", ""
	}
}
