package generators

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/kgsaran/trackfw/internal/pathguard"
)

func GeneratePomXML(cfg Config) error {
	slug := toSlug(cfg.ProjectName)
	if slug == "" {
		slug = "my-app"
	}
	name := cfg.ProjectName
	if name == "" {
		name = "My App"
	}

	content := fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.3.0</version>
    <relativePath/>
  </parent>
  <groupId>com.example</groupId>
  <artifactId>%s</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>%s</name>
  <description>%s — generated by trackfw</description>
  <properties>
    <java.version>21</java.version>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>
</project>
`, slug, name, name)

	// Guard before write: pom.xml is written relative to CWD (= project root).
	// Root: projectRoot() — resolves macOS /tmp→/private/tmp via EvalSymlinks.
	// Guard precedes WriteFile so a refused destination creates no stray file.
	// 🔴 Fail-closed (ML-9A): when the root cannot be established the guard cannot
	// run, so the write is REFUSED instead of proceeding unguarded. Until ML-9A the
	// guard sat inside `if rootErr == nil` while the write sat outside it.
	javaRoot, rootErr := projectRoot()
	if rootErr != nil {
		return pathguard.RefuseUnverifiableRoot("pom.xml", rootErr)
	}
	absPom := filepath.Join(javaRoot, "pom.xml")
	if guardErr := pathguard.RejectAndReport(javaRoot, absPom); guardErr != nil {
		return guardErr
	}
	// write-containment-allowed: pathguard.RejectAndReport(javaRoot, absPom) above dominates this write unconditionally; an unresolvable root refuses via RefuseUnverifiableRoot
	return os.WriteFile("pom.xml", []byte(content), 0644)
}
