package generators

import (
	"os"
	"path/filepath"
	"testing"
)

// TestValidateScriptMembership verifies that checkValidateScriptArtifact accepts
// both the Go/Node form and Python's fixed form, and refuses a near-miss that
// matches neither.
//
// This test is the durability anchor for the set-membership decision (2026-08-27):
// if buildValidateScript or pythonValidateScriptForm changes, this test breaks and
// forces a conscious update of the membership set.
func TestValidateScriptMembership(t *testing.T) {
	cfg := Config{} // no backend/frontend — same as this repo's trackfw.yaml
	goNodeForm := buildValidateScript(cfg)
	pythonForm := pythonValidateScriptForm

	cases := []struct {
		name    string
		content string
		wantNil bool // true = accepted (nil finding), false = accused
	}{
		{
			name:    "Go/Node form accepted",
			content: goNodeForm,
			wantNil: true,
		},
		{
			name:    "Python form accepted",
			content: pythonForm,
			wantNil: true,
		},
		{
			name:    "near-miss Go form (set -x instead of set -e) refused",
			content: "#!/usr/bin/env sh\n# trackfw governance gate — generated by trackfw init\nset -x\n\necho \"→ trackfw: validating governance...\"\ntrackfw validate\n\n\necho \"✓ all checks passed.\"\n",
			wantNil: false,
		},
		{
			name:    "hand-edited content refused",
			content: "trackfw validate\n",
			wantNil: false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			if err := os.MkdirAll(filepath.Join(dir, "scripts"), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(filepath.Join(dir, "scripts/trackfw-validate.sh"), []byte(tc.content), 0o755); err != nil {
				t.Fatal(err)
			}
			finding := checkValidateScriptArtifact(
				filepath.Join(dir, "scripts/trackfw-validate.sh"),
				"scripts/trackfw-validate.sh",
				cfg,
			)
			if tc.wantNil && finding != nil {
				t.Errorf("expected no finding but got: %+v", finding)
			}
			if !tc.wantNil && finding == nil {
				t.Errorf("expected a finding but got nil")
			}
		})
	}
}

// TestValidateScriptMembership_Missing verifies that a missing file produces
// scaffold-missing, not scaffold-divergent.
func TestValidateScriptMembership_Missing(t *testing.T) {
	dir := t.TempDir()
	cfg := Config{}
	finding := checkValidateScriptArtifact(
		filepath.Join(dir, "scripts/trackfw-validate.sh"),
		"scripts/trackfw-validate.sh",
		cfg,
	)
	if finding == nil {
		t.Fatal("expected scaffold-missing finding for absent file, got nil")
	}
	// import integrations to access constant — check the string value directly
	if finding.FindingKind != "scaffold-missing" {
		t.Errorf("expected finding.FindingKind=scaffold-missing, got %q", finding.FindingKind)
	}
}
